services:
  app:
    build: .
    container_name: blog10
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    container_name: blog10-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: blog10
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0000'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog10"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: blog10-redis

volumes:
  pgdata:
